# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: eadesignit
services:
  eadesignit-app:
    image: mauvaisetroupe/ea-design-it
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/EADesignIt
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://postgresql:5432/EADesignIt
    ports:
      - 127.0.0.1:8080:8080
  eadesignit-postgresql:
    image: postgres:14.5
    # volumes:
    #   - ~/volumes/jhipster/EADesignIt/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=EADesignIt
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
    links:
      - 'eadesignit-postgresql:pgsql-server'
      # pgadmin, use 'pgsql-server' as server name
      # https://linuxhint.com/postgresql_docker/
